version: "3.8"

services:
  php:
    build:
      context: ./
      dockerfile: ./.docker/local.Dockerfile
    image: php8.2-base-cev
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: base
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  mysql_volume:
